#### Cluster Subsmission Settings ####
# Name of the queue to which to submit the job
queue_name: "openmpi"
# Name of the command used to submit scripts to the queue
queue_submit_command: "qsub -l gpu=4"
# The template for your standard queue job submission script
queue_submission_template: "/public/EM/RELION/relion/bin/qsub.csh"
# Minimum number of dedicated cores that need to be requested on each node
queue_minimum_dedicated: 32

#### Relion Refine Parameters ####
# Initial low-pass filter for the refinements
refine_ini_lowpass: 15
# Read all particles in one batch into memory?
refine_preread_images: true
# Or copy particles to scratch disk?
refine_scratch_disk: "/scratch/senda-em/"
# Number of pooled particles?
refine_nr_pool: 30
# Use GPU-acceleration?
refine_do_gpu: no
# Which GPU to use (different from GPU used for pre-processing?)
refine_gpu: ""
# How many MPI processes to use
refine_mpi: 3
# How many threads to use
refine_threads: 5
# Skip padding?
refine_skip_padding: true
# Submit jobs to the cluster?
refine_submit_to_queue: false
