#!/usr/bin/env python

import os
import sys
import starfile
import argparse
import fnmatch
import stacksplit_common as ss_comm
import folderfile_common as ff_comm
import split_particles_star as sp_split
import make_sub_folder as ms_folder
import make_link_folder as lin_folder
import edit_scheme_star as es_star
import run_sub_schemes as sub_run
from pathlib import Path


LOG_FILE = 'stacksplit.log'
### SCHEME_COPY_SOURCE = 'Schemes_Edited/Schemes/'
SYMBOLIC_LINK = 'symbolic'
HARD_LINK = 'hard'
MERGE_SETTING_FILE = 'merge_setting.yml'
### MERGE_SCHEME_NODE = '090050_Refine3D_local'
### MERGE_FILE = 'run_data.star'
DEFAULT_STACK_SPLIT_SCHEME_YML_FILENAME = 'stack_split_scheme.yml'
SCHEME_NODE_030060 = '030060_Select_rm_bars_xy'


def get_config_sample_setting_file_name(current_path):
    print('-->get_config_sample_setting_file_name', flush=True)
    
    file_list = [
        f for f in os.listdir(current_path) if os.path.isfile(os.path.join(current_path, f))
    ]

    print(f'[KEK_MESSAGE] FileList: {file_list}', flush=True)
    matched_file = fnmatch.filter(file_list, 'config_sample_settings*.yml')
    print(f'[KEK_MESSAGE] MatchedFile: {matched_file}', flush=True)
    return matched_file

### def validate_args(args):
    ### errors = []
    ### return_flg = True
    ### 
    ### #print('--> validate_args')
    ### ### if args.yml_file is None:
    ###     ### ## 
    ###     ### errors.append('You must be set --yml_file.')
    ###     
    ### #print(f'Error: {len(errors)}')
    ### if errors:
    ###     for err in errors:
    ###         print(err)
    ###     return_flg = False
    ### return return_flg

def write_result_setting_file(current_path, job_name, sub_folder_list, log_file, node_name, merge_file):
    output_path = os.path.join(current_path, job_name)
    output_file_path = os.path.join(output_path, MERGE_SETTING_FILE)
    
    print(f'[KEK_MESSAGE] -->write_result_setting_file')
    print(f'[KEK_MESSAGE] CurrentPath: {current_path}')
    print(f'[KEK_MESSAGE] JobName: {job_name}')
    print(f'[KEK_MESSAGE] SubFolderList: {sub_folder_list}')
    print(f'[KEK_MESSAGE] LogFile: {log_file}')
    print(f'[KEK_MESSAGE] NodeName: {node_name}')
    print(f'[KEK_MESSAGE] MergeFile: {merge_file}')
    print(f'[KEK_MESSAGE] OutputFilePath: {output_file_path}')
    
    setting_data = {
        'setting': {
            'current_path': current_path,
            'sub_folder_name': sub_folder_list,
            'node_name': node_name,
            'merge_file_name': merge_file
        }
    } 
    print(f'[KEK_DEBUG] Setting: {setting_data}')
    ss_comm.write_yaml_file(setting_data, output_file_path)

def main():
    current_path = os.getcwd()
    current_path = current_path.replace('stacksplit_scheme', '')
    current_path = ss_comm.fix_path_end(current_path)

    print(f'[KEK_DEBUG] CurrentPath: {current_path}')
    
    input_parts_star = None
    splits_num = None
    particles_num = None
    scheme_list = []
    scheme_copy_source = None
    merge_scheme_node = None
    merge_file = None
    symbolic_link = None
    
    
    parser = argparse.ArgumentParser()
    
    ### parser.add_argument('-yml', '--yml_file', type=str, default=DEFAULT_STACK_SPLIT_SCHEME_YML_FILENAME, help='Configuration YML file.')
    ### parser.add_argument('-sf', '--star_file', type=str, help='Star file to be split')
    ### parser.add_argument('-spnum', '--splits_num', type=int, help='Number of file splits')
    ### parser.add_argument('-ptnum', '--particles_num', type=int, help='Approximate number of particles per file')
    ### parser.add_argument('-cp', '--scheme_copy_source', type=str, default=SCHEME_COPY_SOURCE, help='CS scheme copy source path')
    ### parser.add_argument('-l', '--link_type', type=str, default=SYMBOLIC_LINK, help='Specify link_type method, "symbolic" or "hard".')

    ### [NOTE: Toshio Moriya (2025/09/14)]
    ### Ideally, the following RELION requirements should be satisfied!
    ### The code will be much simpler too...
    ### parser.add_argument("-i", "--input", "--in_parts",  type=str,  help = "RELION requirement! Input particle star file Path (relative)")
    ### parser.add_argument("-o", "--output",              type=str,  help = "RELION requirement! Output job directory path (relative)")
    ### [Reference 2025/09/16] RELION Documentation > Using RELION > The External job-type
    ### https://relion.readthedocs.io/en/latest/Reference/Using-RELION.html
    
    ### 2025/09/16 Example of command line generated by RELION
    ### $ ../stacksplit_scheme/stack_split_scheme.py    \
    ###     --o External/job011/    \
    ###     --in_parts Select/job010/particles.star    \
    ###     --splits_num 2    \
    ###     --particles_num -1    \
    ###     --scheme_list 060_CSS_Clean_Stack_3D,070_CSS_Init_Refine3D,080_CSS_PPRefine_Cycle,090_CSS_Res_Fish_3D    \
    ###     --scheme_copy_source Schemes_Edited/Schemes/    \
    ###     --link symbolic    \
    ###     --merge_scheme_node 090050_Refine3D_local    \
    ###     --merge_file run_data.star    \
    ###     --j 1 
    
    parser.add_argument('-i', '--input', '--in_parts',  type=str, required=True, help = 'RELION requirement! Input particles star file path to be split (relative path).')
    parser.add_argument('-o', '--output',               type=str, required=True, help = 'RELION requirement! Output job directory path (relative path).')
    parser.add_argument('-spnum', '--splits_num',       type=int, default=None,  help = 'Number of file splits. (default specified in stack_split_scheme.yml).')
    parser.add_argument('-ptnum', '--particles_num',    type=int, default=None,  help = 'Approximate number of particles per file. ((default specified in stack_split_scheme.yml).')
    parser.add_argument('-sl', '--scheme_list',         type=str, default=None,  help = 'List of Schemes to run in parallel. (default specified in stack_split_scheme.yml).')
    parser.add_argument('-cp', '--scheme_copy_source',  type=str, default=None,  help = 'CS scheme copy source path. (default specified in stack_split_scheme.yml).')
    parser.add_argument('-l', '--link_type',            type=str, default=None,  help = 'Specify link type, "symbolic" or "hard". (default specified in stack_split_scheme.yml).')
    parser.add_argument('-msn', '--merge_scheme_node',  type=str, default=None,  help = 'Specify scheme node to be merged. (default specified in stack_split_scheme.yml).')
    parser.add_argument('-mf', '--merge_file',          type=str, default=None,  help = 'Specify STAR file to be merged.  (default specified in stack_split_scheme.yml).')

    args, unknown = parser.parse_known_args()
    print(f'[KEK_MESSAGE] Running Stack Split Scheme...')
    print(f'[KEK_MESSAGE] ', flush=True)

    ### print(f'[KEK_DEBUG] Entry YmlFile: {args.yml_file}')
    print(f'[KEK_DEBUG] Entry InputPartsStar: {args.input}')
    print(f'[KEK_DEBUG] Entry OutputDir: {args.output}')
    print(f'[KEK_DEBUG] Entry SplitsNum: {args.splits_num}')
    print(f'[KEK_DEBUG] Entry ParticlesNum: {args.particles_num}')
    print(f'[KEK_DEBUG] Entry SchemeList: {args.scheme_list}')
    print(f'[KEK_DEBUG] Entry SchemeCopySource: {args.scheme_copy_source}')
    print(f'[KEK_DEBUG] Entry Link: {args.link_type}')
    print(f'[KEK_DEBUG] Entry Link: {args.merge_scheme_node}')
    print(f'[KEK_DEBUG] Entry Link: {args.merge_file}')
    print(f'[KEK_DEBUG] ', flush=True)

    own_job_name = None
    own_job_path = None
    own_job_no = None

    sub_folder_list = []
    copy_file_list = ['default_pipeline.star']
   
    try:
        ### [NOTE: Toshio Moriya (2025/09/14)]
        ### The following code is not necessary only if it satisfies RELION requirement as mentioned above!
        ### Thus, the code will be much simpler too...
        ### parser.add_argument("-o", "--output",              type=str,  help = "RELION requirement! Output job directory path (relative)")
        ### 
        ## own_job_name = ss_comm.get_own_job(current_path)
        own_job_name = args.output
        ## debug
        #own_job_name = 'External/job200/'
        
        ### if own_job_name is not None: 
        ###     own_job_path = os.path.join(current_path, own_job_name)
        ###     own_job_no = own_job_name[-4:-1]
        ### else:
        ###     raise Exception(f'[KEK_ERROR] Job name could not be obtained.')
        
        assert own_job_name is not None, f'# Logical Error: own_job_name must not be None at this point of code!.'
        own_job_path = os.path.join(current_path, own_job_name)
        own_job_no = own_job_name[-4:-1]    # External/job###/
        # NOTE: Toshio Moriya (2025/09/16)
        # The above code looses the general pattern...
        # Must be revised later!
        
        print(f'[KEK_DEBUG] JobFullPath: {own_job_path}')
        print(f'[KEK_DEBUG] JobName: {own_job_name}')
        print(f'[KEK_DEBUG] JobNo: {own_job_no}')
        
        # Set the path of star file from an arugment
        input_parts_star = args.input

        # Get the path of this script file
        script_file_path = Path(__file__).resolve()
        print(f'[MRK_DEBUG] Script File Path of this script: {script_file_path}')
        script_dir_path = script_file_path.parent
        print(f'[MRK_DEBUG] Script Directory Path of this script: {script_dir_path}')
        # Generate the file path of default stac split scheme config YAML file
        default_yml_file_path = script_dir_path / DEFAULT_STACK_SPLIT_SCHEME_YML_FILENAME        # パス結合は / 演算子でOK
        assert os.path.exists(default_yml_file_path), f'# Logical Error: Default YAML config file {script_dir} must exit!.'
        
        # Load contents of YAML file into varaibles
        ### yml_setting = ss_comm.load_yaml_file(args.yml_file)
        yml_setting = ss_comm.load_yaml_file(default_yml_file_path)
        setting_data = yml_setting['setting']
        #print(f'Setting: {setting_data}')
        ### input_parts_star = setting_data['input_parts_star']
        splits_num = setting_data['splits_num']
        particles_num = setting_data['particles_num']
        scheme_list = setting_data['scheme_list']
        scheme_copy_source = setting_data['scheme_copy_source']
        link_type = setting_data['link_type']
        merge_scheme_node = setting_data['merge_scheme_node']
        merge_file = setting_data['merge_file']
        
        print(f'[KEK_MESSAGE] Loaded values from YAML file:')
        print(f'[KEK_MESSAGE]   SplitsNum: {splits_num}')
        print(f'[KEK_MESSAGE]   ParticlesNum: {particles_num}')
        print(f'[KEK_MESSAGE]   SchemesList: {scheme_list}')
        print(f'[KEK_MESSAGE]   SchemeCopySource: {scheme_copy_source}')
        print(f'[KEK_MESSAGE]   LinkType: {link_type}')
        print(f'[KEK_MESSAGE]   MergeSchemeNode: {merge_scheme_node}')
        print(f'[KEK_MESSAGE]   MergeFile: {merge_file}', flush=True)
        print(f'[KEK_MESSAGE] ', flush=True)
        
        # If specified by command line, override argument values of YAML config file
        print(f'[KEK_MESSAGE] ')
        print(f'[KEK_MESSAGE] Checking command line arguments...')
        print(f'[KEK_MESSAGE] ', flush=True)
        ### if args.input is not None:
        ###     input_parts_star = args.input
        if args.splits_num is not None and args.splits_num > 0:
            print(f'[KEK_MESSAGE] Overwride with command line splits_num: {splits_num}')
            splits_num = args.splits_num
        if args.particles_num is not None and args.particles_num > 0:
            print(f'[KEK_MESSAGE] Overwride with command line particles_num: {particles_num}')
            particles_num = args.particles_num
        if args.scheme_copy_source is not None:
            print(f'[KEK_MESSAGE] Overwride with command line scheme_copy_source: {scheme_copy_source}')
            scheme_copy_source = args.scheme_copy_source
        if args.scheme_list is not None:
            print(f'[KEK_MESSAGE] Overwride with command line scheme_list: {scheme_list}')
            scheme_list = args.scheme_list.split(",")
        if args.link_type is not None:
            print(f'[KEK_MESSAGE] Overwride with command line link_type: {link_type}')
            link_type = args.link_type
        if args.merge_scheme_node is not None:
            print(f'[KEK_MESSAGE] Overwride with command line merge_scheme_node: {merge_scheme_node}')
            merge_scheme_node = args.merge_scheme_node
        if args.merge_file is not None:
            print(f'[KEK_MESSAGE] Overwride with command line merge_file: {merge_file}')
            merge_file = args.merge_file
        print(f'[KEK_MESSAGE] ', flush=True)
            
        # Convert Link Type from string ("symbolic" or "hard") to bool
        symbolic_link = True
        link_type = str.lower(args.link_type)
        if link_type == HARD_LINK:
            symbolic_link = False
        ### else:  # link_type == SYMBOLIC_LINK:
            ### symbolic_link = True
        
        ### if input_parts_star is None:
            ### current_schemes_030_path = os.path.join(current_path, 'Schemes/030_GTF_Create_Stack/')
            ### run_out_030 = os.path.join(current_schemes_030_path, 'run.out')
            ### target_node_name = SCHEME_NODE_030060
            ### target_job_name = ss_comm.extract_job_name_from_file(run_out_030, target_node_name)
            ### 
            ### input_parts_star = os.path.join(current_path, target_job_name)
            ### input_parts_star = os.path.join(input_parts_star, 'particles.star')
        ### if scheme_copy_source is None:
            ### scheme_copy_source = SCHEME_COPY_SOURCE
        ### if len(scheme_list) == 0:
            ### scheme_list = ['060_CSS_Clean_Stack_3D', '070_CSS_Init_Refine3D', '080_CSS_PPRefine_Cycle', '090_CSS_Res_Fish_3D']
        ### if merge_scheme_node is None:
            ### merge_scheme_node = MERGE_SCHEME_NODE
        ### if merge_file is None:
            ### merge_file = MERGE_FILE
        
        ### flg = validate_args(args)
        ### if not flg:
        ###     raise Exception
        if splits_num is None and particles_num is None:
            raise Exception(f'[KEK_ERROR] You must be set, splits_num or particles_num.')
        
        print(f'[KEK_MESSAGE] Applied argument values:')
        print(f'[KEK_MESSAGE]   InputPartsStar: {input_parts_star}')
        print(f'[KEK_MESSAGE]   SplitsNum: {splits_num}')
        print(f'[KEK_MESSAGE]   ParticlesNum: {particles_num}')
        print(f'[KEK_MESSAGE]   SchemeList: {scheme_list}')
        print(f'[KEK_MESSAGE]   SchemeCopySource: {scheme_copy_source}')
        print(f'[KEK_MESSAGE]   LinkType: {link_type}(SymbolicLink: {symbolic_link})')
        print(f'[KEK_MESSAGE]   MergeSchemeNode: {merge_scheme_node}')
        print(f'[KEK_MESSAGE]   MergeFile: {merge_file}')
        print(f'[KEK_MESSAGE] ', flush=True)
        
        config_file_list = get_config_sample_setting_file_name(current_path)
        for file in config_file_list:
            copy_file_list.append(file)
        print(f'[KEK_DEBUG] CopyFileList: {copy_file_list}')
        print(f'[KEK_DEBUG] ', flush=True)

        # Debug
        #sys.exit(0)

        ## split star file
        sub_folder_list = sp_split.split_particles_star(current_path, input_parts_star, own_job_no, splits_num, particles_num)
        
        print(f'[KEK_DEBUG] SubFolderList: {sub_folder_list}')
        print(f'[KEK_DEBUG] SchemeList: {scheme_list}')
        
        sub_folder_abs_list = []
        
        for sub_folder in sub_folder_list:
            sub_folder_path = os.path.join(current_path, sub_folder)
            sub_folder_abs_list.append(sub_folder_path)
            print(f'[KEK_DEBUG] SubFolderPath: {sub_folder_path}')
            ms_folder.make_sub_folder(current_path, sub_folder_path, copy_file_list, scheme_copy_source, scheme_list)
            lin_folder.make_link_folder(current_path, sub_folder_path, symbolic_link)
            ## split star file
            split_star_file = os.path.join(sub_folder_path, sub_folder.replace('/', '') + '.star')
            es_star.edit_scheme_star(current_path, sub_folder_path, split_star_file)
                       
        print(f'[KEK_MESSAGE] Scheme is ready to be activated!')
        print(f'[KEK_MESSAGE] ', flush=True)
        
        ## Execute scheme_list
        success_flg = sub_run.run_sub_schemes(sub_folder_abs_list, scheme_list, LOG_FILE)
        if not success_flg:
            raise Exception(f'[KEK_ERROR] Error with subfolder scheme.')
        
        ## Write result config to YAML file
        write_result_setting_file(current_path, own_job_name, sub_folder_list, LOG_FILE, merge_scheme_node, merge_file)
        
        open(os.path.join(own_job_path, 'RELION_JOB_EXIT_SUCCESS'), 'w').close()
    except Exception as e:
        print(f'Exception: {e}')
        if own_job_path: 
            open(os.path.join(own_job_path, 'RELION_JOB_EXIT_FAILURE'), 'w').close()
            sys.exit(0)

if __name__ == "__main__":
    main()
